# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DLDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DLDemo
	pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket', # needed for debugging
    'RCTNetwork', # this is the missing one!!
    # Add any other subspecs you want to use in your project
  ]
  
end
